# Generated by Django 6.0.2 on 2026-02-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0)),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
