# Generated by Django 6.0.3 on 2026-03-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='prazo_validade_dias',
            field=models.IntegerField(default=30, verbose_name='Prazo de Validade (dias)'),
        ),
    ]
