# Generated by Django 6.0.3 on 2026-03-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_prazo_validade_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Última Compra'),
        ),
    ]
