# Generated by Django 6.0.2 on 2026-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='categorias_fornecidas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='itens_fornecidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_entrega_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_fornecimento',
            field=models.CharField(choices=[('PRODUTOS', 'Produtos'), ('SERVICOS', 'Serviços'), ('AMBOS', 'Produtos e Serviços')], default='PRODUTOS', max_length=20),
        ),
    ]
