# Generated by Django 6.0.2 on 2026-03-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_categorias_fornecidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='prazo_entrega_dias',
        ),
    ]
