# Generated by Django 6.0.3 on 2026-03-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_telefone'),
        ('produtos', '0003_produto_data_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco unitario')),
                ('data_venda', models.DateField(verbose_name='Data da venda')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
