# Generated by Django 6.0.3 on 2026-03-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='prazo_validade_dias',
            field=models.IntegerField(default=30, verbose_name='Prazo de Validade (dias)'),
        ),
    ]
