# Generated by Django 6.0.3 on 2026-03-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_prazo_validade_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='prazo_validade_dias',
        ),
    ]
